'use client';
import {useEffect,useState} from 'react';
const initial={from:'',to:'',grain:'day',user:''};
export default function Report(){
 const [filters,setFilters]=useState(initial),[applied,setApplied]=useState(initial),[data,setData]=useState(null),[page,setPage]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[detail,setDetail]=useState(null);
 async function load(f=filters,p=0){setBusy(true);setError('');setDetail(null);try{
  const r=await fetch('/api/admin/report?'+new URLSearchParams({...f,page:String(p)}),{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j);setApplied(f);setPage(p);
 }catch(e){setError(e.message||'เชื่อมต่อไม่ได้');}finally{setBusy(false);}}
 useEffect(()=>{load(initial);},[]);
 async function open(id){setBusy(true);setError('');try{const r=await fetch('/api/history?admin=1&id='+id,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setDetail(j);}catch(e){setError(e.message);}finally{setBusy(false);}}
 const date=value=>new Date(value).toLocaleString('th-TH',{timeZone:'Asia/Bangkok'});
 return <main className="shell"><div className="header"><div><h1>รายงานการสร้างสคริปต์</h1><p>สำหรับแอดมิน • วันที่ตามเวลาไทย</p></div><a className="secondary" href="/">กลับหน้าสร้างสคริปต์</a></div>
 <section className="profilePanel"><form onSubmit={e=>{e.preventDefault();load(filters);}}><div className="row"><div className="field"><label className="label" htmlFor="from">ตั้งแต่วันที่</label><input className="input" id="from" type="date" value={filters.from} onChange={e=>setFilters({...filters,from:e.target.value})}/></div><div className="field"><label className="label" htmlFor="to">ถึงวันที่ (รวมวันนี้)</label><input className="input" id="to" type="date" value={filters.to} onChange={e=>setFilters({...filters,to:e.target.value})}/></div><div className="field"><label className="label" htmlFor="grain">สรุปตาม</label><select className="select" id="grain" value={filters.grain} onChange={e=>setFilters({...filters,grain:e.target.value})}><option value="day">วัน</option><option value="month">เดือน</option><option value="year">ปี</option></select></div></div><div className="actions"><button className="primary" disabled={busy}>ดูรายงาน</button><button type="button" className="secondary" disabled={busy} onClick={()=>{setFilters(initial);load(initial);}}>ดูทั้งหมด</button></div></form><p>นับเฉพาะการสร้างสำเร็จที่บันทึกประวัติแล้ว • ปกติ 1 ครั้ง = 3 สคริปต์ • เว้นวันที่ว่างเพื่อดูทั้งหมด</p><p role="alert">{error}</p>{busy&&<p role="status">กำลังโหลด…</p>}</section>
 {data&&<><section className="profilePanel"><h2>{data.generations.toLocaleString()} ครั้ง · {data.scripts.toLocaleString()} สคริปต์</h2><p>ยอดรวมในช่วงวันที่และผู้ใช้ที่เลือก {applied.user&&'• กำลังกรองสมาชิกหนึ่งคน'}</p><h3>แยกตามสมาชิก</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>สมาชิก</th><th>ครั้ง</th><th>สคริปต์</th><th>ประวัติ</th></tr></thead><tbody>{data.people.map(p=><tr key={p.user_id}><td>{p.email||p.user_id}</td><td>{p.generations}</td><td>{p.scripts}</td><td><button className="textButton" disabled={busy} onClick={()=>{const f={...applied,user:p.user_id};setFilters(f);load(f);}}>ดูสมาชิกนี้</button></td></tr>)}</tbody></table></div><h3>แยกตาม{applied.grain==='day'?'วัน':applied.grain==='month'?'เดือน':'ปี'}</h3><div style={{overflowX:'auto',maxHeight:320}}><table style={{width:'100%',textAlign:'left'}}><thead><tr><th>ช่วงเวลา (ค.ศ.)</th><th>ครั้ง</th><th>สคริปต์</th></tr></thead><tbody>{data.periods.map(p=><tr key={p.period}><td>{p.period.slice(0,applied.grain==='year'?4:applied.grain==='month'?7:10)}</td><td>{p.generations}</td><td>{p.scripts}</td></tr>)}</tbody></table></div>{!data.generations&&<p>ไม่พบประวัติในช่วงที่เลือก</p>}</section>
 <section className="profilePanel"><h2>ประวัติการสร้าง</h2>{data.items.map(x=><button key={x.id} disabled={busy} className="secondary" style={{display:'block',width:'100%',textAlign:'left',marginBottom:8}} onClick={()=>open(x.id)}>{x.title}<small style={{display:'block'}}>{x.email} · {date(x.created_at)} · {x.scripts} สคริปต์</small></button>)}<div className="actions"><button className="secondary" disabled={busy||page===0} onClick={()=>load(applied,page-1)}>ก่อนหน้า</button><span>หน้า {page+1}</span><button className="secondary" disabled={busy||(page+1)*20>=data.generations} onClick={()=>load(applied,page+1)}>ถัดไป</button></div></section></>}
 {detail&&<section className="profilePanel"><button className="secondary" onClick={()=>setDetail(null)}>ปิดรายละเอียด</button><h2>{detail.title}</h2><p>{date(detail.created_at)}</p><details><summary>ข้อมูลต้นเรื่อง</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(detail.input,null,2)}</pre></details>{detail.output.directions?.map((d,i)=><article key={i}><h3>แบบ {i+1} · {d.title}</h3><p style={{whiteSpace:'pre-wrap'}}>{d.script}</p><details><summary>Hook, Caption และข้อมูลทั้งหมด</summary><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(d,null,2)}</pre></details></article>)}</section>}
 </main>;
}
