'use client';
import {useState} from 'react';
export default function AccountBar({email,onOpen,revision}){
  const [items,setItems]=useState([]),[page,setPage]=useState(0),[shown,setShown]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function load(p=0){setBusy(true);setMessage('');try{const r=await fetch('/api/history?page='+p,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);setItems(j.items);setPage(p);setShown(true);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  async function open(id){setBusy(true);try{const r=await fetch('/api/history?id='+id,{cache:'no-store'});const j=await r.json();if(!r.ok)throw new Error(j.error);onOpen(j);setShown(false);}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  async function logout(){setBusy(true);try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'logout'})});if(!r.ok)throw new Error('ออกจากระบบไม่สำเร็จ กรุณาลองอีกครั้ง');window.location.replace('/login');}catch(e){setMessage(e.message);setBusy(false);}}
  return <section className="profilePanel"><div className="actions" style={{justifyContent:'space-between',flexWrap:'wrap'}}><span>{email}</span><div className="actions"><button className="secondary" disabled={busy} onClick={()=>shown?setShown(false):load()}>ประวัติของฉัน</button><button className="textButton" disabled={busy} onClick={logout}>ออกจากระบบ</button></div></div><p role="status">{message}</p>{shown&&<div><h2>ประวัติการสร้างสคริปต์</h2>{items.length===0&&<p>ยังไม่มีประวัติในหน้านี้</p>}{items.map(x=><button className="secondary" style={{display:'block',width:'100%',textAlign:'left',marginBottom:8}} key={x.id} disabled={busy} onClick={()=>open(x.id)}>{x.title}<small style={{display:'block'}}>{new Date(x.created_at).toLocaleString('th-TH')}</small></button>)}<div className="actions"><button className="secondary" disabled={busy||page===0} onClick={()=>load(page-1)}>ก่อนหน้า</button><button className="secondary" disabled={busy||items.length<20} onClick={()=>load(page+1)}>ถัดไป</button></div></div>}</section>;
}
